### PR TITLE
Add support for instantclient

### PR DESCRIPTION
**Pull request by jonlawlor**
I've added some modified scripts that download the instant client, sdk, and sqlplus.  It is (at least) partially duplicative of XE, so I'm not sure it should be a part of the travis-oracle repo - maybe a travis-oracle-instantclient repo?

The immediate use for this was to get http://github.com/mattn/go-oci8 building on travis.

As you can probably see the code is seriously violating DRY.  It might make more sense to just put all 3 packages into a single download and install script, and just have one environment variable to explain the version number.

### CODE REVIEW

**Comment by jonlawlor** [comment]
This is a followup to #2

**Comment by cbandy** [comment]
I think it makes sense for the client tools to be in this repo.

> It might make more sense to just put all 3 packages into a single download and install script, and just have one environment variable to explain the version number.

That seems like the right approach to me too. Should it be possible to install each one of these things separately (basic, sdk, sql*plus) or does one typically install two (or all three?) I expect we should keep the server and client as separate choices.

**Comment by jonlawlor** [comment]
For my use I only needed the basic + sdk, but the instructions I find usually include sql*plus, so I suspect that is a common use case.  It is only an additional 800kb or so, so I figure bundling them makes more sense.

We could always do something fancy like checking to see if the environment variable identifying the sdk or sql plus files exist, and if so, downloading and installing them.  Something like

``` bash
if [ -z "$ORACLE_INSTANTCLIENT_SDK_FILE" ]; then
   download_instantclient_sdk.sh
   install_instantclient_sdk.sh
fi
```

**Comment by jonlawlor** [comment]
Is there anything I can do for this?  This isn't meant to poke you along; I just have some free time.

**Comment by cbandy** [comment]
Sorry for the delay, I've been looking at oci8 modules/packages to understand the differences between the full client that comes with XE and the instant client. It seems that files end up in different places for different clients and different versions.

Regarding what's here,
1. I'd like to compare the contents of these zip and rpm downloads to see if there is any benefit to just using the zips. Are you familiar enough with rpm or dpkg to help with that?
2. `download.js` can probably be fixed take a few arguments, but I don't know how to do that in node/phantom atm.
3. There are quite a few clients available to download... how should we expose the choice to the user?

**Comment by jonlawlor** [comment]
- I picked the rpm's because their file size was slightly smaller.  For the basic lite client, it is about 400k.  Nothing to write home about, but without a reason to choose either that seemed like a sensible choice.  I've never used alien before.
- I don't really know javascript very well but I can take a shot.
- Maybe providing a list of packages with a path separator, and then feeding the names to the script in no. 2?

**Comment by jonlawlor** [comment]
Parameterizing download.js looks straightforward.  I'll submit a pull request sometime later today, hopefully.

**Comment by cbandy** [comment]
It seems overkill to script the Instant Client install because the RPMs have almost no prerequisites (only one library.) I've decided to extend `download.sh` to make it easy to get the RPMs, then leave it to the user to execute `sudo rpm --install` right in `.travis.yml`. We can keep the [wiki](https://github.com/cbandy/travis-oracle/wiki) up-to-date with instructions. Let me know what you think.

**Comment by jonlawlor** [comment]
Sounds good to me!

**Pull request closed without merging**
