### PR TITLE
update reference to download.js

### PR DESCRIPTION
**Pull request by jonlawlor**
If you follow the directions on the readme, you put the download.js into the .travis/oracle directory.  phantomjs can't find it in the current command.

### CODE REVIEW

**Comment by jonlawlor** [comment]
Aha, so this is the exact opposite problem as I encountered.  It might be useful to put the .sh and .js scripts into a .travis/oracle/ directory here as well.

**Comment by cbandy** [comment]
I might have a solution that works for both locations. I'll have a look today.

**Comment by jonlawlor** [comment]
Thanks!

Incidentally, I adapted your javascript to be able to download and install the oracle instant client & sdk.  Would you like to own the code in your github account?  I'm no javascript or bash expert.  Alternatively I can put it into a repo and attribute you.

**Comment by cbandy** [comment]
This is fixed on the latest master, however I found another issue that I'd like to address before another release.

> I adapted your javascript to be able to download and install the oracle instant client & sdk.

Nice! Please open another issue or pull request and we can discuss there.

**Pull request closed without merging**
